import json
import logging
from datetime import datetime
from typing import Dict, Any, List
from dataclasses import dataclass

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("ReportGenerator")

@dataclass
class ReportSection:
    title: str
    content: str
    level: str  # 'executive', 'technical', 'remediation'

class SecurityReportGenerator:
    """
    Industrial-grade reporting engine. 
    Converts raw AI findings into professional, structured security audits.
    """
    
    def __init__(self, target_id: str):
        self.target_id = target_id
        self.sections: List[ReportSection] = []

    def add_section(self, title: str, content: str, level: str = 'technical'):
        self.sections.append(ReportSection(title, content, level))

    def generate_markdown(self) -> str:
        """
        Generates a high-professional Markdown report suitable for GitHub 
        or conversion to PDF.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report = [
            f"# 🛡️ SOVEREIGN SECURITY AUDIT: {self.target_id}",
            f"**Date:** {timestamp}",
            f"**Classification:** CONFIDENTIAL // RED TEAM OPERATION",
            "\n---",
            "## 1. Executive Summary",
            "This document outlines the results of an autonomous security assessment. "
            "The objective was to identify critical attack paths and provide strategic remediation."
        ]

        # Logic to split and format sections by level
        for section in self.sections:
            prefix = "###" if section.level == 'technical' else "##"
            report.append(f"\n{prefix} {section.title}\n{section.content}")

        report.append("\n---")
        report.append("**End of Report | Generated by RedTeam AI Sovereign Engine**")
        
        return "\n".join(report)

    def generate_json_artifact(self) -> str:
        """Generates a machine-readable JSON artifact for SIEM integration."""
        data = {
            "target": self.target_id,
            "generated_at": datetime.now().isoformat(),
            "findings": [
                {"title": s.title, "content": s.content, "level": s.level} 
                for s in self.sections
            ]
        }
        return json.dumps(data, indent=4)

if __name__ == "__main__":
    # Quick test of the generator
    gen = SecurityReportGenerator("10.0.0.5")
    gen.add_section("Threat Score", "Score: 92/100 - Critical", "executive")
    gen.add_section("Attack Path", "SSH -> SMB RCE -> DC", "technical")
    print(gen.generate_markdown())
